// client/src/pages/SignIn.jsx
import React, { useContext, useState } from 'react';
import {MDBBtn, MDBInput} from 'mdbreact';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import {useToasts} from 'react-toast-notifications';
import '../styles/signin.scss';

export const SignIn = () => {

    const [loader, setLoader] = useState(false);
    const [form, setForm] = useState({
        email: '',
        password: ''
    });
    const auth = useContext(AuthContext);
    const {addToast} = useToasts();

    function changeHandler(event){

        setForm({...form, [event.target.name]: event.target.value});
    }

    async function sendForm(event){

        event.preventDefault();

        setLoader(true);
        axios.post('/api/auth/signin', form, {headers: {'Content-Type': 'application/json'}})
        .then(response => {
            
            const {userId, token} = response.data;
            auth.login(userId, token);
        })
        .catch(error => {
            addToast(error.response.data.message, {appearance: "error"});
        })
        .finally(() => {setLoader(false)});
    }

    return (
        <div className="container">
            <div className="row d-flex justify-content-center">

                <div className="auth">
                        <div className="auth__header">
                            <div className="auth__header__overlay">
                                <h2>Вход в систему</h2>
                            </div>
                        </div>
                    
                    <div className="auth__body">

                        <form onSubmit={sendForm}>
                            <div className="grey-text">
                                <MDBInput label="Email" icon="envelope" group type="email" validate error="wrong"
                                    success="right" name="email" value={form.email} onChange={changeHandler} required/>
                                
                                <MDBInput label="Пароль" icon="lock" group type="password" 
                                    validate name="password" value={form.password} onChange={changeHandler}/>
                            </div>
                            <div className="text-center">
                                <MDBBtn color="success" type={loader ? "button" : "submit"} disabled={loader} 
                                    className="auth__btn">
                                {loader ? 
                                    <>
                                        <span className="spinner-border spinner-border-sm mr-2" role="status" aria-hidden="true"></span>
                                        Обработка...</> 
                                    :
                                        <span>Войти  <i className="fa fa-key"/></span>}
                                </MDBBtn>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    );
}

// client/src/app/auth/sign-in/sign-in.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { Subject } from 'rxjs';
import { takeUntil, finalize, catchError } from 'rxjs/operators';
import { ToastService } from 'src/app/shared/services/toast.service';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss'],
})
export class SignInComponent implements OnInit, OnDestroy {
  signInForm: FormGroup;
  loader: boolean = false;
  unsubscribe: Subject<void> = new Subject<void>();

  constructor(
    private authService: AuthService,
    private toastService: ToastService,
    private router: Router
  ) {}

  ngOnDestroy(): void {
    this.unsubscribe.next();
    this.unsubscribe.complete();
  }

  ngOnInit(): void {
    if(this.authService.isAuthenticated()){
      this.router.navigate(['']);
    }
    this.signInForm = new FormGroup({
      email: new FormControl(null, [Validators.required]),
      password: new FormControl(null, [Validators.required]),
    });
  }

  signIn() {
    if (this.signInForm.invalid) return;

    this.loader = true;
    this.authService.login(this.signInForm.value.email, this.signInForm.value.password)
    .pipe(finalize(() => {this.loader = false}), takeUntil(this.unsubscribe))
    .subscribe(() => {},
      response => {
        this.toastService.show('error', response.error.message)});
  }
}

<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="auth">
      <div class="auth__header">
        <div class="auth__header__overlay">
          <h2>Вход в систему</h2>
        </div>
      </div>

      <div class="auth__body">
        <form [formGroup]="signInForm" (ngSubmit)="signIn()">
          <div class="grey-text">
            <div class="md-form">
              <mdb-icon fas icon="envelope" class="prefix"></mdb-icon>
              <input mdbInput type="email" formControlName="email" id="email" class="form-control">
              <label for="email" class="">Email</label>
            </div>
            <div class="md-form">
              <mdb-icon fas icon="lock" class="prefix"></mdb-icon>
              <input mdbInput formControlName="password" type="password" id="password" class="form-control">
              <label for="password" class="">Пароль</label>
            </div>
          </div>
          <div class="text-center">
            <button mdbBtn color="success" type="submit"
              [disabled]="loader" class="rounded-btn">

              <span *ngIf="!loader; else loading">Войти <i class="fa fa-key"></i></span>
              <ng-template #loading>
                <span class="spinner-border spinner-border-sm mr-2" role="status"
                  aria-hidden="true"></span>
              </ng-template>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
